spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
  aop:
    proxy-target-class: true
    auto: true
server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 100000
mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.hh.his.graduationproject.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
  page-size-zero: true

